//! # Pipeline Artifacts
//! 
//! This module defines the persistent artifacts generated by the Titan Engine, 
//! such as `manifest.json` and `run_results.json`.

pub mod manifest;
pub mod run_results;
pub use manifest::Manifest;
pub use run_results::RunResults;
